/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-05-24 01:14:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class user_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/it/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("file:/C:/Users/it/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1557969813632L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Instagram</title>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/image/user/favicon.ico\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\"\r\n");
      out.write("\trel=\"stylesheet\" />\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: rgb(250, 250, 250);\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".body {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("\tmargin-top: 94.961px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photo1 {\r\n");
      out.write("\tdisplay:grid;\r\n");
      out.write("\tgrid-template-columns: auto auto auto;\r\n");
      out.write("\tgrid-gap : 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upperbox1 {\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tborder-bottom: 1px solid rgb(220, 220, 220);\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tz-index: 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".semibox {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 1000px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upperbox2 {\r\n");
      out.write("\tpadding: 24px 20px;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: 3fr 2fr 3fr;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".upperbox2 * {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uppervalue1 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uppervalue3 {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: auto auto auto;\r\n");
      out.write("\tjustify-content: end;\r\n");
      out.write("\tgrid-gap: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value1image1 {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: -2px;\r\n");
      out.write("\tleft: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value1image2 {\r\n");
      out.write("\tbackground-color: rgb(80, 80, 80);\r\n");
      out.write("\theight: 28px;\r\n");
      out.write("\twidth: 1px;\r\n");
      out.write("\tmargin: 0 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value1image3 {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 5px;\r\n");
      out.write("\tleft: -5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uppervalue2 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value2image1 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 90%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value2image2 {\r\n");
      out.write("\tborder: 1px solid rgb(220, 220, 220);\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tbackground-color: rgb(250, 250, 250);\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".uppervalue3 {\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value3image1 * {\r\n");
      out.write("\tmargin: 0 8px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value3image2 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: rgb(56, 151, 240);\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder-style: none;\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value3image3 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\tcolor: rgb(56, 151, 240);\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("\tborder-style: none;\r\n");
      out.write("\tpadding: 8px 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".value2image2:active .material-icons {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".material-icons {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\ttop: 14px;\r\n");
      out.write("\tleft: 10px;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bodypadding {\r\n");
      out.write("\tpadding: 0 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile {\r\n");
      out.write("\tpadding: 20px 50px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: auto auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".profile * {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".thumbnail {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 200px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button4 {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tbackground-color: rgb(250, 250, 250);\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tborder-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button4:hover .loginback {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button4:hover .body {\r\n");
      out.write("\topacity: 0.2;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".explorer {\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\theight: 150px;\r\n");
      out.write("\tborder: 1px solid;\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-image: url(\"/image/user/profile.jpg\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".name {\r\n");
      out.write("\tmargin-right: 15px;\r\n");
      out.write("\tfont-size: 28px;\r\n");
      out.write("\tfont-weight: 100;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rower {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\tmargin-bottom: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rower2 {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rower3 {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".rower * {\r\n");
      out.write("\tmargin-right: 20px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".linkbox {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".links {\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding: 0 45px 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".links * {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".deco {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".deco1 {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tborder-top: 1px solid black;\r\n");
      out.write("\ttop: -24px;\r\n");
      out.write("\tleft: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".deco2 {\r\n");
      out.write("\tcolor: grey;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link1 {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\tborder: 1px solid rgb(220, 220, 220);\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-image: url(\"/image/user/Personal.jpg\");\r\n");
      out.write("\tbackground-position: center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link2 {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\tborder: 1px solid rgb(220, 220, 220);\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-image: url(\"/image/user/Features.jpg\");\r\n");
      out.write("\tbackground-position: center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link3 {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\tborder: 1px solid rgb(220, 220, 220);\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-image: url(\"/image/user/Facebook.jpg\");\r\n");
      out.write("\tbackground-position: center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".link4 {\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("\theight: 80px;\r\n");
      out.write("\tborder: 1px solid rgb(220, 220, 220);\r\n");
      out.write("\tborder-radius: 50%;\r\n");
      out.write("\tbackground-image: url(\"/image/user/hwak.jpg\");\r\n");
      out.write("\tbackground-position: center center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lining {\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".lining * {\r\n");
      out.write("\tpadding: 0 30px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photo * {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 1fr;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("\tmargin: 0 0 15px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photo * * {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tmargin: 0 15px 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photobox {\r\n");
      out.write("\tbackground-color: black;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photobox:hover .photoimage {\r\n");
      out.write("\topacity: 0.4;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".photobox:hover .score {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".score {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tpadding: 150px 0 0 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".scorein {\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tmargin: 15px;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("\tmargin: 0 45px 0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footerbox {\r\n");
      out.write("\tpadding: 40px 0;\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: 5fr 1fr\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footerbox ul {\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("\tfont-weight: 550;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footerbox ul li {\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("\tpadding: 7px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footerbox ul li a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".copyright {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: grey;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".topbox {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top1 {\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tborder-radius: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top2 {\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("\theight: 100px;\r\n");
      out.write("\tborder-radius: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text1box {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tvertical-align: top;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text1 {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: 1000;\r\n");
      out.write("\tdisplay: inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text2 {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text3 {\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("\twidth: 600px;\r\n");
      out.write("\theight: 1000px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("article {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground-color: white;\r\n");
      out.write("\twidth: 430px;\r\n");
      out.write("\theight: 600px;\r\n");
      out.write("\tborder-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("\tfont-size: 45px;\r\n");
      out.write("\tmargin: 10px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=text] {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tbackground-color: #FAFAFA;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tborder: 1px solid whitesmoke;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=password] {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tbackground-color: #FAFAFA;\r\n");
      out.write("\tfont-size: 15px;\r\n");
      out.write("\tborder: 1px solid whitesmoke;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=submit] {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\theight: 45px;\r\n");
      out.write("\tbackground-color: #3897f0;\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\tpadding: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sliceline {\r\n");
      out.write("\tdisplay: grid;\r\n");
      out.write("\tgrid-template-columns: 3fr 2fr 3fr;\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sliceline * {\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".slice {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tbackground-color: gray;\r\n");
      out.write("\theight: 1px;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\ttop: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".face {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bin {\r\n");
      out.write("\tbackground-color: #FAFAFA;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("\tborder: 1px solid whitesmoke;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".click1 {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #385185;\r\n");
      out.write("\tfont-size: 18px;\r\n");
      out.write("\tfont-weight: 600;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".click2 {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #385185;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".click3 {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #385185;\r\n");
      out.write("\tfont-size: 19px;\r\n");
      out.write("\tfont-weight: 700;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginback {\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tz-index: 2;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".logmain {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\tpadding-top: 120px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"upperbox1\">\r\n");
      out.write("\t\t<div class=\"semibox\">\r\n");
      out.write("\t\t\t<div class=\"upperbox2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"uppervalue1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"value1image1\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/image/user/icon.png\" onclick=\"location.href='/images'\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"value1image2\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"value1image3\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"/image/user/instagram.png\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"location.href='/images'\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"uppervalue2\">\r\n");
      out.write("\t\t\t\t\t<i class=\"material-icons\">search</i>\r\n");
      out.write("\t\t\t\t\t<div class=\"value2image1\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"value2image2\" type=\"text\" placeholder=\"검색\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"uppervalue3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"value1image1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/explore\"><img src=\"/image/images/41.png\"/></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"value1image1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\"><img src=\"/image/images/42.png\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"value1image1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/user/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img src=\"/image/images/43.png\" /></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<main class=\"body\">\r\n");
      out.write("\t<div class=\"bodypadding\">\r\n");
      out.write("\t\t<div class=\"profile\">\r\n");
      out.write("\t\t\t<div class=\"thumbnail\">\r\n");
      out.write("\t\t\t\t<div class=\"explorer\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t<div class=\"rower\">\r\n");
      out.write("\t\t\t\t\t<div class=\"name\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"rower\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t게시물\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${imageCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t팔로워\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${followerCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t팔로우\r\n");
      out.write("\t\t\t\t\t\t<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${followCount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"rower2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"rower3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" ↟</div>\r\n");
      out.write("\t\t\t\t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.bio }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" <br /> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.website }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.website }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<hr />\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"lining\">\r\n");
      out.write("\t\t\t<div class=\"deco\">\r\n");
      out.write("\t\t\t\t<div class=\"deco1\"></div>\r\n");
      out.write("\t\t\t\t<div>🎞 게시물</div>\r\n");
      out.write("\t\t\t\t<div class=\"deco2\">🖼 태그됨</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"photo\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- photo item -->\r\n");
      out.write("\t\t\t<div class=\"photo1\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- end photo item -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t<div class=\"footerbox\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">INSTAGRAM 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">지원</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">홍보 센터</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">API</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">채용 정보</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">개인정보처리방침</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">약관</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">디렉터리</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">프로필</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">해시태그</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"#\">언어</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<div class=\"copyright\">ⓒ 2019 INSTAGRAM</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer> </main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/user/user.jsp(592,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id ne user.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<!-- Follow 유무 체크해야함. -->\r\n");
          out.write("\t\t\t\t\t\t\t\t<button class=\"value3image2\">팔로우</button>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<button class=\"value3image2\">프로필편집</button>\r\n");
          out.write("\t\t\t\t\t\t\t\t<button class=\"value3image2\" onclick=\"location.href='/image/upload'\">사진업로드</button>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/user/user.jsp(642,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("item");
      // /WEB-INF/views/user/user.jsp(642,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/user/user.jsp(642,4) '${imageList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${imageList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t<div class=\"photobox\">\r\n");
            out.write("\t\t\t\t\t\t<div class=\"score\">\r\n");
            out.write("\t\t\t\t\t\t\t<div class=\"scorein\">💖");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.likeCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("\t\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t\t\t<img class=\"photoimage\" src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.filePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("\t\t\t\t\t</div>\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
