/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-05-24 01:14:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.auth;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Document</title> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\" integrity=\"sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf\" crossorigin=\"anonymous\">\r\n");
      out.write("    <style>\r\n");
      out.write("        *{\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("        body{\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background-color: rgb(250, 250, 250);\r\n");
      out.write("        }\r\n");
      out.write("        main{\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            height: 800px\r\n");
      out.write("        }\r\n");
      out.write("        .container{\r\n");
      out.write("            width: 700px;\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            display: grid;\r\n");
      out.write("            grid-template-columns: auto auto;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            grid-column-gap: 30px;\r\n");
      out.write("            grid-row-gap: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        .instagram{\r\n");
      out.write("            grid-row: 1/4 span;\r\n");
      out.write("            margin-top: 30%\r\n");
      out.write("        }\r\n");
      out.write("        .image{\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .bigbox{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            grid-column: 2/1 span;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .smallbox{\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        .table{\r\n");
      out.write("            margin: 10px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("        }\r\n");
      out.write("        .text{\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("            margin: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .hr{\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            font-size: 12px;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=text]{\r\n");
      out.write("            height: 31.3px;\r\n");
      out.write("            width: 268.02px;\r\n");
      out.write("            background-color: rgb(250, 250, 250);\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            padding: 19px;\r\n");
      out.write("            margin: 2px;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("        input[type=password]{\r\n");
      out.write("            height: 31.3px;\r\n");
      out.write("            width: 268.02px;\r\n");
      out.write("            background-color: rgb(250, 250, 250);\r\n");
      out.write("            border: 1px solid lightgray;\r\n");
      out.write("            padding: 19px;\r\n");
      out.write("            margin: 2px;\r\n");
      out.write("        }\r\n");
      out.write("        input[type=button], input[type=submit]{\r\n");
      out.write("            height: 31.3px;\r\n");
      out.write("            width: 268.02px;\r\n");
      out.write("            background-color: #3897F0;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            color: white;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        i{\r\n");
      out.write("            height: 31.3px;\r\n");
      out.write("            width: 268.02px;\r\n");
      out.write("            background-color: #3897F0;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 9px 0px;\r\n");
      out.write("        }\r\n");
      out.write("      .get{\r\n");
      out.write("          display: grid;\r\n");
      out.write("          grid-template-columns: auto auto auto;\r\n");
      out.write("          grid-gap: 10px;\r\n");
      out.write("      }\r\n");
      out.write("      footer{\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: relative;\r\n");
      out.write("      }\r\n");
      out.write("      .under{\r\n");
      out.write("        grid-column: 1/2 span;\r\n");
      out.write("        \r\n");
      out.write("       \r\n");
      out.write("      }\r\n");
      out.write("      .under li{\r\n");
      out.write("          display: inline-block;\r\n");
      out.write("          padding: 5px;\r\n");
      out.write("          margin-top: 60px;\r\n");
      out.write("      }\r\n");
      out.write("      .under1{\r\n");
      out.write("          font-size: 10px;\r\n");
      out.write("          text-decoration: none;\r\n");
      out.write("          color: skyblue;\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"instagram\"><img src=\"/image/auth/insta.png\" alt=\"x\" width=\"300\" height=\"500\" ></div>\r\n");
      out.write("        <div class=\"bigbox\">\r\n");
      out.write("            <div><img src=\"/image/auth/font.png\" alt=\"x\" class=\"image\"></div>\r\n");
      out.write("            <p class=\"text\">친구들의 사진과 동영상을 보려면 가입하세요.</p>\r\n");
      out.write("            <div><a href=\"#\"><i class=\"fab fa-facebook-square\"> Facebook으로 로그인</i></a></div>\r\n");
      out.write("            <div class=\"text\"><hr class=\"hr\" />  또는  <hr class=\"hr\" /></div>\r\n");
      out.write("            <form action=\"/auth/create\" method=\"post\">\r\n");
      out.write("\t            <table class=\"table\">\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td><input type=\"text\" name=\"email\" placeholder=\"이메일 주소\" ></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td><input type=\"text\" name=\"name\" placeholder=\"성명\" ></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td><input type=\"text\" name=\"username\" placeholder=\"사용자 이름\" ></td>\r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t                <tr>\r\n");
      out.write("\t                    <td><input type=\"password\" name=\"password\" placeholder=\"비밀번호\" ></td> \r\n");
      out.write("\t                </tr>\r\n");
      out.write("\t            </table>\r\n");
      out.write("\t            <input type=\"submit\" value=\"가입\">\r\n");
      out.write("            </form>\r\n");
      out.write("            <p class=\"text\">가입하면 Instagram의 약관, 데이터 정책 및 쿠키 정책에 동의하게 됩니다.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"smallbox\">\r\n");
      out.write("        <div class=text>계정이 있으신가요? <a href=\"/auth/login\" class=\"under1\">로그인</a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <P class=\"text\">앱을 다운로드 하세요</P>\r\n");
      out.write("        <div class=\"get\">\r\n");
      out.write("            <div class=\"get1\"><a href=\"#\"><img src=\"/image/auth/apple.png\" alt=\"\"></a></div>\r\n");
      out.write("            <div class=\"get1\"><a href=\"#\"><img src=\"/image/auth/google.png\" alt=\"\"></a></div>\r\n");
      out.write("            <div class=\"get1\"><a href=\"#\"><img src=\"/image/auth/micro.png\" alt=\"\"></a></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"under\">\r\n");
      out.write("                <ui>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">지원</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">홍보 센터</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">API</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">채용 정보</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">개인정보처리방침</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">약관</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">디렉터리</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">프로필</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">해시태그</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">언어</a></li>\r\n");
      out.write("                <li><a href=\"#\" class=\"under1\">INSTGRAM 정보</a></li>\r\n");
      out.write("            </ui>\r\n");
      out.write("        </div> \r\n");
      out.write("    </div>\r\n");
      out.write("               \r\n");
      out.write("        \r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
